<?php

return [
    'casas-asuncion' => [
        'title' => 'Casas à Venda em Asunción | Imóveis no Paraguai 2025',
        'description' => 'Encontre casas à venda em Asunción. Imóveis de qualidade no Paraguai para brasileiros investirem.',
        'h1' => 'Casas à Venda em Asunción',
        'city_id' => 40,
        'category_slug' => 'casas',
    ],
    'apartamentos-asuncion' => [
        'title' => 'Apartamentos à Venda em Asunción | Imóveis Paraguai',
        'description' => 'Apartamentos novos e usados à venda em Asunción.',
        'h1' => 'Apartamentos à Venda em Asunción',
        'city_id' => 40,
        'category_slug' => 'apartamentos',
    ],
    'terrenos-asuncion' => [
        'title' => 'Terrenos à Venda em Asunción | Comprar Terreno Paraguai',
        'description' => 'Terrenos à venda em Asunción para construção.',
        'h1' => 'Terrenos à Venda em Asunción',
        'city_id' => 40,
        'category_slug' => 'terrenos',
    ],
    'casas-luque' => [
        'title' => 'Casas à Venda em Luque | Imóveis Paraguai',
        'description' => 'Casas à venda em Luque, cidade próxima a Asunción.',
        'h1' => 'Casas à Venda em Luque',
        'city_id' => 49,
        'category_slug' => 'casas',
    ],
    'terrenos-luque' => [
        'title' => 'Terrenos à Venda em Luque | Paraguai',
        'description' => 'Terrenos em Luque para construção.',
        'h1' => 'Terrenos à Venda em Luque',
        'city_id' => 49,
        'category_slug' => 'terrenos',
    ],
    'quintas-luque' => [
        'title' => 'Quintas à Venda em Luque | Chácaras Paraguai',
        'description' => 'Quintas e chácaras à venda em Luque.',
        'h1' => 'Quintas à Venda em Luque',
        'city_id' => 49,
        'category_slug' => 'quintas',
    ],
    'casas-san-bernardino' => [
        'title' => 'Casas à Venda em San Bernardino | Imóveis Paraguai',
        'description' => 'Casas à venda em San Bernardino.',
        'h1' => 'Casas à Venda em San Bernardino',
        'city_id' => 48,
        'category_slug' => 'casas',
    ],
    'quintas-san-bernardino' => [
        'title' => 'Quintas à Venda em San Bernardino | Paraguai',
        'description' => 'Quintas de veraneio em San Bernardino.',
        'h1' => 'Quintas à Venda em San Bernardino',
        'city_id' => 48,
        'category_slug' => 'quintas',
    ],
    'alugueis-casas-asuncion' => [
        'title' => 'Casas para Alugar em Asunción | Aluguel Paraguai',
        'description' => 'Casas para alugar em Asunción. Aluguel de imóveis no Paraguai.',
        'h1' => 'Casas para Alugar em Asunción',
        'city_id' => 40,
        'category_slug' => 'casas',
    ],
    'alugueis-apartamentos-asuncion' => [
        'title' => 'Apartamentos para Alugar em Asunción | Paraguai',
        'description' => 'Apartamentos para alugar em Asunción.',
        'h1' => 'Apartamentos para Alugar em Asunción',
        'city_id' => 40,
        'category_slug' => 'apartamentos',
    ],
    'alugueis-casas-luque' => [
        'title' => 'Casas para Alugar em Luque | Aluguel Paraguai',
        'description' => 'Casas para alugar em Luque.',
        'h1' => 'Casas para Alugar em Luque',
        'city_id' => 49,
        'category_slug' => 'casas',
    ],
    'alugueis-apartamentos-luque' => [
        'title' => 'Apartamentos para Alugar em Luque | Paraguai',
        'description' => 'Apartamentos para alugar em Luque.',
        'h1' => 'Apartamentos para Alugar em Luque',
        'city_id' => 49,
        'category_slug' => 'apartamentos',
    ],
];
